### ISSUE TITLE
coreutils: currently fails with configure fails with error: could not determine how to read list of mounted file systems #58

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/coreutilsport#1]
"./configure" --prefix=/home/itodoro/zot/prod/coreutils-9.1 CC=njsc "CPPFLAGS=-DNSIG=9 -D_XOPEN_SOURCE=600 -D_ALL_SOURCE -D_OPEN_SYS_FILE_EXT=1 -D_AE_BIMODAL=1 -D_ENHANCED_ASCII_EXT=0xFFFFFFFF" "CFLAGS=" CXX=njsc++ "CXXFLAGS=" "LDFLAGS= "

configure fails with error: could not determine how to read list of mounted file systems #58

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM the current patch to configure to get this to 'configure' actually causes a link error downstream I think:
```
 IEW2456E 9207 SYMBOL free_mount_entry UNRESOLVED.  MEMBER COULD NOT BE INCLUDED
          FROM THE DESIGNATED CALL LIBRARY.
 IEW2456E 9207 SYMBOL read_file_system_list UNRESOLVED.  MEMBER COULD NOT BE
          INCLUDED FROM THE DESIGNATED CALL LIBRARY.
FSUM3065 The LINKEDIT step ended with return code 8.
```

so we need a smaller sledge hammer I think so that we can get at least these services (or alternately, remove code that references those services)

**Comment by MikeFultonDev** [comment]
Routine that maybe we could use for getmntinfo: 
https://www.ibm.com/docs/en/zos/2.5.0?topic=functions-w-getmntent-get-information-mounted-file-systems
