### ISSUE TITLE
timeout of 'sleep' does not work

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/coreutilsport#19]
There are testcases that expect timeout to be able to stop a child process doing a sleep.

Here is the testcase (make sure you get both the 'timeout' and the 'sleep' from coreutils):

```
src/timeout 0.1 ./src/sleep 1d 2h 3m 4s
```
The above hangs (sleeps) even though it should finish in 0.1s

Note that (I think) 'sleep' is fine because if I run this in the background and send a simple 'kill' to sleep (which will send a SIGTERM) then it terminates, e.g.

```
src/timeout 0.1 ./src/sleep 1d 2h 3m 4s &
```
kill <sleep pid>

will cancel everything.

Note that `src/timeout --signal=9 1 ./src/sleep 1d 2h 3m 4s ` also sleeps

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM @jshimoda9323 @ccw-1 @AnthonyGiorgio  if anyone knows a little about signals, would love your ideas here since 'a little' would put you ahead of me...

**Comment by MikeFultonDev** [comment]
@ccw-1 shared an older version that works. After a bit of comparison, I confirmed that not using the setitimer and using the 1s resolution 'alarm' does the trick. So - temporary fix to use alarm although we should figure out why setitimer doesn't work.

**Comment by MikeFultonDev** [comment]
@HarithaIBM is this still an issue?

**Comment by MikeFultonDev** [comment]
@HarithaIBM is this still an issue?

**Comment by HarithaIBM** [comment]
I donot see this issue anymore, i ran the below command manually from coreutils.
src/timeout 0.1 ./src/sleep 1d 2h 3m 4s
