### ISSUE TITLE
More than 350 test cases are failing in coreutils - chmod functionality is failing in ~ > 40 test cases

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/coreutilsport#24]
I have analysed the test logs of more than 40 in misc / rm /chmod directories in coreutils and i see a common error in the failing test cases:

+ chmod -R u+rwx /home/haritha/code/coreutilsport/coreutils-9.1/gt-yes.sh.wj2q
chmod: /home/haritha/code/coreutilsport/coreutils-9.1/gt-yes.sh.wj2q: EDC5113I Bad file descriptor.
+ rm -rf /home/haritha/code/coreutilsport/coreutils-9.1/gt-yes.sh.wj2q
rm: traversal failed: /home/haritha/code/coreutilsport/coreutils-9.1/gt-yes.sh.wj2q: EDC5113I Bad file descriptor.
+ test 1 = 0
+ exit 1

**Comment by MikeFultonDev** [comment]
closing because we now have 63 tests failing - so assume fixed - @HarithaIBM re-open if still an issue
