### ISSUE TITLE
od does not work if input file is not ISO8859-1

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/coreutilsport#38]
autoconversion is being done which is not appropriate for a hex dump utility

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM fyi

**Comment by gngrossi** [comment]
bash-5.2$ ls -lT zopen_QQQ.special.1047
t IBM-1047    T=on  -rw-r--r--   1 @02858   @ISCICS1      16 Apr  1 11:55 zopen_QQQ.special.1047

bash-5.2$ which od
/hewitt/zopentools/guild/coreutils-9.1/bin/od

bash-5.2$ od -hc zopen_QQQ.special.1047
**0000000    7e20    5e20    2120    7c20    5b20    5d20    a220    ac0a**
          ~       ^       !       |       [       ]     242     254  \n
0000020

bash-5.2$ /bin/od -hc zopen_QQQ.special.1047
0000000000    A1  40  5F  40  5A  40  4F  40  AD  40  BD  40  4A  40  B0  15
               ~       ^       !       |       [       ]     112     260  \n
0000000020

**Comment by gngrossi** [comment]
RC=(0) [SYSA] bash-5.2$ which od
/hewitt/zopentools/guild/coreutils-9.1/bin/od

RC=(0) [SYSA] bash-5.2$ od --version
od (GNU coreutils) 9.1

RC=(0) [SYSA] bash-5.2$ ls -T XX*
t ISO8859-1   T=on  XX
t IBM-1047    T=on  XX.ebcdic

RC=(0) [SYSA] bash-5.2$ cat XX*
A B C
A B C

RC=(0) [SYSA] bash-5.2$ od -hc XX
0000000    4120    4220    430a
          A       B       C  \n
0000006

RC=(0) [SYSA] bash-5.2$ od -hc XX.ebcdic
0000000    c140    c240    c315
        301   @ 302   @ 303 025
0000006

--
# using /bin/od
RC=(0) [SYSA] bash-5.2$ /bin/od -hc XX.ebcdic
0000000000    C1  40  C2  40  C3  15
               A       B       C  \n
0000000006

**Comment by IgorTodorovskiIBM** [comment]
I believe this is working with /bin/od because /bin/od is an EBCDIC application. But if you run `/bin/od -hc XX`, where XX is your ascii file, I believe /bin/od will not auto-convert the ASCII characters. 

We would need to add extra code to auto-convert the block array based on the original file when printing the characters.

**Comment by gngrossi** [comment]
In this example, is this expectation when running the od port, the character portion of the output would render the same for  ascii and ebcdic?  thanks
 A       B       C  \n

--

RC=(0) [SYSA] bash-5.2$ ls -T XX*
t ISO8859-1   T=on  XX
t IBM-1047    T=on  XX.ebcdic

# running /bin/od
RC=(0) [SYSA] bash-5.2$ /bin/od -hc XX
0000000000    41  20  42  20  43  0A
             101 040 102 040 103 012
0000000006

RC=(0) [SYSA] bash-5.2$ /bin/od -hc XX.ebcdic
0000000000    C1  40  C2  40  C3  15
               A       B       C  \n
0000000006

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM just to confirm: it appears that https://github.com/ZOSOpenTools/coreutilsport/blob/main/patches/PR9/disableautoconversion_for_binary_tools.patch should fix the original bug I opened this against which was that conversion was happening for od. True? If so, I'm thinking it might make sense to close this issue as 'fixed' and open a new issue that we should respect the file tag when printing out 'text' for the -c option (e.g. if the stream is tagged X (e.g. 1047), use X as the 'text' ccsid for printing the characters?
