### ISSUE TITLE
uptime/users/who fail because of /etc/utmp: EDC5121I Invalid argument

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/coreutilsport#39]
Culprit appears to be:
```
fopen (file, "re");
```
in readutmp.c.

```
JrEdc1opsEinval02: The mode argument passed to fopen() or freopen() contained
more information than just the open mode, but did not use a comma to separate
the additional keywords.
```

**Comment by IgorTodorovskiIBM** [comment]
Another issue:
By default coreutils processes /etc/utmp. Changing it to /etc/utmpx helps, but the strings being returned from getutxent are in EBCDIC. We may need to override getutxent/setutxent in zoslib as there are quite a few tools that use these functions.

**Comment by MikeFultonDev** [comment]
closing since code merged for it. @IgorTodorovskiIBM re-open if necessary
