### ISSUE TITLE
ptx - EDC5121I Invalid argument

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/coreutilsport#47]
bash-5.2$ ptx -A /tmp/gary/Z
ptx: /tmp/gary/Z: EDC5121I Invalid argument.

# using stdin
bash-5.2$ ptx -A
/tmp/gary/Z
:1:                      /tmp/gary/   Z
:1:                           /tmp/   gary/Z
:1:                               /   tmp/gary/Z

**Comment by IgorTodorovskiIBM** [comment]
> Any update? thanks

Hey, no update as of yet. I'm not very familiar with ptx. Do you have a use case for it?

**Comment by IgorTodorovskiIBM** [comment]
```
[ITODORO@ZOSCAN2B ~/projects/coreutilsport_new2/coreutils-9.1-prev/src]$ ./ptx -A cp
ptx: cp: EDC5121I Invalid argument. (errno2=0xC00B0022)
[ITODORO@ZOSCAN2B ~/projects/coreutilsport_new2/coreutils-9.1-prev/src]$ bpxmtext C00B0022

JrEdc1opsEinval02: The mode argument passed to fopen() or freopen() contained
more information than just the open mode, but did not use a comma to separate
the additional keywords.

Action: Correct the mode argument. White-space characters are not permitted
within the open mode. The 't' specification is not allowed for POSIX(OFF)
applications. Separate the open mode from the remaining keywords with a comma.
 Note that it could be possible that the open mode itself is not correct.

Source: edc1opst.c
```

**Comment by MikeFultonDev** [comment]
Using https://unix.stackexchange.com/questions/92730/usr-bin-ptx-can-you-provide-a-use-case-or-two as an example,
it seems to be working ok... I created /tmp/gary/A with the contents:
```
a
b
c
```

and got as output:
```
ptx /tmp/gary/A
                                       a b c
                                   a   b c
                                 a b   c
```

with the latest build (9.4 coreutils, october 5th)

Does this look right now @gngrossi ?
