### ISSUE TITLE
cp error using -O c=utf-8 for a PDS member

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/coreutilsport#53]
# Is this expected?
bash-5.2$ cp -O c=utf-8 "//'@02858.T.COZ.SAMPLIB(QQQ)'" GG11
cp: FSUMF192 fcntl() failed and could not set autoconversion for GG11: EDC5121I Invalid argument.

bash-5.2$ /bin/cp -O c=utf-8 "//'@02858.T.COZ.SAMPLIB(QQQ)'" GG11
cp: FSUMF192 fcntl() failed and could not set autoconversion for GG11: EDC5121I Invalid argument.

# works
bash-5.2$ cp -O c=utf-8 "//'@02858.T.S3TEST.SPECIAL'" GG10
bash-5.2$ /bin/cp -O c=utf-8 "//'@02858.T.S3TEST.SPECIAL'" GG10a

**Comment by MikeFultonDev** [comment]
@gngrossi i hadn't read this closely enough before. So you are saying that both cp and /bin/cp do not work for the PDS member, correct? If so, then this is a bug against z/OS shells and utilities, not z/OS Open Tools.
If I am misreading, please tell me.

**Comment by MikeFultonDev** [comment]
Would you be willing to open a problem report against the z/OS Shell and Utilities? Then we could reference that number here and safely close this? I don't want the bug to 'disappear' ...

**Comment by gngrossi** [comment]
I will open a problem ticket against the z/OS Shell and Utilities.
Closing.
thanks

**Comment by gngrossi** [comment]
Closing.
