### ISSUE TITLE
Will these commands that overlap with /bin be part of altbin?

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/coreutilsport#73]
@IgorTodorovskiIBM 
![image](https://github.com/ZOSOpenTools/coreutilsport/assets/115715798/abefcc12-c6b3-4243-bb7c-776618373c3c)
![image](https://github.com/ZOSOpenTools/coreutilsport/assets/115715798/399314af-7993-420e-ab1b-158623d0198f)

**Comment by gngrossi** [comment]
The ls command is now ls (GNU coreutils) 9.5
...will there be an option to display file tag information?

thanks

**Comment by IgorTodorovskiIBM** [comment]
My mistake! I pushed a change to fix it: https://github.com/ZOSOpenTools/coreutilsport/commit/f4873a5c27b4adfedc11584d1372e9dcd479b6cc - the build takes ~10 hours. I'll remove this bad release.

**Comment by gngrossi** [comment]
Back to coreutils  9.4.20231116_212509 ?
thanks

**Comment by gngrossi** [comment]
Upgraded...thanks
