### ISSUE TITLE
install does not copy file tag

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/coreutilsport#9]
```
echo "asdf" > a.txt
chtag -tc 819 a.txt
install a.txt b.txt
ls -lT
```

Output is:
```
ls -lT *.txt
t ISO8859-1   T=on  -rw-rw-r--   1 ITODORO  CDEV           5 Aug 19 14:58 a.txt
- untagged    T=off -rwxr-xr-x   1 ITODORO  CDEV           5 Aug 19 14:58 b.txt
```

**Comment by MikeFultonDev** [comment]
Note this also causes issues for rsync because it is trying to use the header file xxhash.h (among others) but it 'looks like' garbage because it isn't tagged as ASCII after install...

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM fyi

**Comment by IgorTodorovskiIBM** [comment]
The issue seems to only occur for ibm-1047 tagged files now, working on a fix

**Comment by IgorTodorovskiIBM** [comment]
fixed with https://github.com/ZOSOpenTools/coreutilsport/commit/ebd98544fd0cff4ae3c5585c4b17cd0f7c210294
